services:
  backend:
    build:
      context: ./backend
    container_name: file-desensitization-backend
    environment:
      UPLOAD_DIR: /app/uploads
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    container_name: file-desensitization-frontend
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  backend_uploads:
