const rows = [
  ['title', '文件脱敏与还原工具', 'File Redaction and Restoration', 'Anonymisation et restauration de fichiers', 'Обезличивание и восстановление файлов', 'إخفاء بيانات الملفات واستعادتها'],
  ['eyebrow', '产品 / 测试版', 'PRODUCT / BETA', 'PRODUIT / BÊTA', 'ПРОДУКТ / БЕТА', 'المنتج / إصدار تجريبي'],
  ['intro', '识别、复核和替换文件中的敏感信息。上传文件后查看检测结果，可手动添加或取消脱敏项，确认后生成脱敏结果与映射表。通过本机历史记录或映射表还原内容。该应用纯本地运行。', 'Identify, review and replace sensitive information in files. Upload a file, review detections, add or remove items, then confirm to generate a redacted file and a mapping table. Restore content using local history or a mapping table. All file processing runs locally.', 'Identifiez, vérifiez et remplacez les informations sensibles. Importez un fichier, examinez les détections, ajoutez ou retirez des éléments, puis confirmez pour générer le fichier anonymisé et sa table de correspondance. Restaurez le contenu depuis l’historique local ou une table. Le traitement des fichiers est entièrement local.', 'Находите, проверяйте и заменяйте конфиденциальные данные в файлах. Загрузите файл, проверьте результаты, добавьте или исключите элементы и подтвердите создание обезличенного файла и таблицы соответствий. Восстанавливайте данные из локальной истории или таблицы. Обработка файлов выполняется локально.', 'حدّد المعلومات الحساسة في الملفات وراجعها واستبدلها. ارفع ملفًا، وراجع النتائج، وأضف العناصر أو أزلها، ثم أكّد إنشاء الملف المخفي البيانات وجدول المطابقة. استعد المحتوى باستخدام السجل المحلي أو جدول المطابقة. تتم معالجة الملفات محليًا بالكامل.'],
  ['navigation', '工作流导航', 'Workflow navigation', 'Navigation des processus', 'Навигация по процессам', 'التنقل بين مسارات العمل'],
  ['redactLabel', '进入脱敏工作流', 'Open redaction workflow', 'Ouvrir le processus d’anonymisation', 'Открыть обезличивание', 'فتح مسار إخفاء البيانات'],
  ['redactTitle', '脱敏工作流', 'Redaction workflow', 'Processus d’anonymisation', 'Обезличивание', 'مسار إخفاء البيانات'],
  ['redactIntro', '上传受支持的文件，查看检测结果；人工确认后生成脱敏结果与映射表。', 'Upload a supported file and review detections. Confirm the items to generate a redacted file and a mapping table.', 'Importez un fichier compatible et vérifiez les détections. Confirmez les éléments pour créer le fichier anonymisé et sa table de correspondance.', 'Загрузите поддерживаемый файл и проверьте результаты. Подтвердите элементы для создания обезличенного файла и таблицы соответствий.', 'ارفع ملفًا مدعومًا وراجع النتائج، ثم أكّد العناصر لإنشاء ملف مخفي البيانات وجدول مطابقة.'],
  ['detect', '常用敏感字段检测', 'Detect common sensitive fields', 'Détecter les champs sensibles courants', 'Поиск распространённых чувствительных полей', 'اكتشاف الحقول الحساسة الشائعة'],
  ['review', '人工添加或取消脱敏项', 'Manually add or exclude items', 'Ajouter ou exclure des éléments manuellement', 'Добавление и исключение элементов вручную', 'إضافة العناصر أو استبعادها يدويًا'],
  ['history', '本机保存脱敏历史', 'Keep redaction history locally', 'Conserver l’historique localement', 'Локальное хранение истории', 'حفظ السجل محليًا'],
  ['enter', '进入工作流', 'Get started', 'Commencer', 'Начать', 'البدء'],
  ['restoreLabel', '进入还原工作流', 'Open restoration workflow', 'Ouvrir le processus de restauration', 'Открыть восстановление', 'فتح مسار الاستعادة'],
  ['restoreTitle', '还原工作流', 'Restoration workflow', 'Processus de restauration', 'Восстановление', 'مسار الاستعادة'],
  ['restoreIntro', '选择本机脱敏历史，或上传脱敏文件与对应映射表，按映射关系还原内容。', 'Choose local redaction history, or upload a redacted file and its mapping table to restore the original values.', 'Sélectionnez l’historique local ou importez un fichier anonymisé avec sa table de correspondance pour restaurer les valeurs originales.', 'Выберите локальную историю или загрузите обезличенный файл с таблицей соответствий для восстановления исходных значений.', 'اختر سجلًا محليًا أو ارفع الملف المخفي البيانات وجدول المطابقة لاستعادة القيم الأصلية.'],
  ['localMapping', '本机映射表直接还原', 'Restore with local mappings', 'Restaurer avec les correspondances locales', 'Восстановление по локальным соответствиям', 'الاستعادة باستخدام المطابقات المحلية'],
  ['placeholders', '占位符逆向替换', 'Replace placeholders with original values', 'Remplacer les marqueurs par les valeurs originales', 'Замена маркеров исходными значениями', 'استبدال العلامات بالقيم الأصلية'],
  ['mappingRecords', '映射记录管理', 'Manage mapping records', 'Gérer les correspondances', 'Управление записями соответствий', 'إدارة سجلات المطابقة'],
  ['usage', '使用说明：', 'Usage: ', 'Utilisation : ', 'Использование: ', 'الاستخدام: '],
  ['usageText', '无需登录。在“敏感字段”中维护规则；规则与脱敏历史保存在本机。处理前请确认当前运行环境符合你的数据安全要求。', 'No login required. Manage rules under Sensitive fields. Rules and redaction history are stored on this device. Check that the environment meets your data security requirements before processing.', 'Aucune connexion requise. Gérez les règles dans Champs sensibles. Les règles et l’historique sont conservés sur cet appareil. Vérifiez que l’environnement répond à vos exigences de sécurité avant le traitement.', 'Вход не требуется. Управляйте правилами в разделе «Чувствительные поля». Правила и история хранятся на этом устройстве. Перед обработкой убедитесь, что среда соответствует вашим требованиям безопасности.', 'لا يلزم تسجيل الدخول. أدِر القواعد في «الحقول الحساسة». تُحفظ القواعد والسجلات على هذا الجهاز. تأكد من ملاءمة بيئة التشغيل لمتطلبات أمان بياناتك قبل المعالجة.']
]
export default Object.fromEntries(['zh', 'en', 'fr', 'ru', 'ar'].map((locale, i) => [locale, { home: Object.fromEntries(rows.map(row => [row[0], row[i + 1]])) }]));
